version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Testing environment variables
          command: |
            echo ${ENGINE} 
      - run:
          name: Running tests and linting code
          command: |
            . venv/bin/activate
            python3 manage.py test
            autopep8 -d -r --exit-code api/ authentication/ ssd/
      - store_artifacts:
          path: test-reports/
          destination: python_app

workflows: # a single workflow with a single job called build
  build:
    jobs:
      - build:
          context: default