# Generated by Django 3.2.7 on 2021-09-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210930_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='astronaut_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.systemuser'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='scientist_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.systemuser'),
        ),
    ]
