# Generated by Django 3.2.7 on 2021-09-30 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210930_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronaut',
            name='astronaut_user',
        ),
        migrations.RemoveField(
            model_name='astronaut',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='scientist_user',
        ),
        migrations.AddField(
            model_name='astronaut',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientist',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
