# Generated by Django 3.2.7 on 2021-10-07 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210930_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronaut',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='astronaut',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='astronaut',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='astronaut',
            name='muscle_mass',
        ),
        migrations.RemoveField(
            model_name='astronaut',
            name='weight',
        ),
        migrations.CreateModel(
            name='AstronautHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('blood_type', models.CharField(max_length=10)),
                ('blood_pressure', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('muscle_mass', models.FloatField()),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.astronaut')),
            ],
        ),
    ]
