# Generated by Django 3.2.7 on 2021-10-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_healthreportfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthreportfeedback',
            name='astronaut_health_report',
        ),
        migrations.AddField(
            model_name='healthreportfeedback',
            name='astronaut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.astronaut'),
            preserve_default=False,
        ),
    ]
