# Generated by Django 3.2.7 on 2021-10-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20211015_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthReportFeedBack',
        ),
    ]
